### DISCUSSION TITLE
Why does my fastlane build_apk failed to install Android SDK when I run my pipeline in Gitlab?

### DISCUSSION THREAD

**Discussion by Weeli-MC** [TheWidlarzGroup/react-native-video#3883] [Q&A]
### What are you trying to do?

Build an Android APK via fastlane (`fastlane build_apk`) in a GitLab CI pipeline. The build works fine on the local machine, but in the GitLab pipeline it fails while configuring `:react-native-video`.

### What have you tried?

Running the fastlane command in a GitLab CI job (image `openjdk:11-jdk`) that installs the Android SDK command-line tools, accepts licenses, and installs `platforms;android-33`, `platform-tools`, and `build-tools;33.0.3` before building. The build fails when configuring the `:react-native-video` project, reporting that `build-tools;30.0.3` could not be installed.

#### Expected vs actual

- Expected: the APK builds successfully in CI, as it does locally.
- Actual: build fails during configuration of `:react-native-video` with a failure to install `build-tools;30.0.3`.

### Relevant code

Error output:

```
> Configure project :react-native-video
useExoplayerIMA:false
Warning: Dependant package with key emulator not found!
FAILURE: Build failed with an exception.
* What went wrong:
Could not determine the dependencies of task ':app:lintVitalReportRelease'.
> Failed to install the following SDK components:
      build-tools;30.0.3 Android SDK Build-Tools 30.0.3
  Install the missing components using the SDK manager in Android Studio.
```

`gitlab.config.yml` (relevant code):

```
variables:
  LANG: "en_US.UTF-8"
  ANDROID_COMPILE_SDK: "33"
  ANDROID_BUILD_TOOLS: "33.0.3"
  ANDROID_SDK_TOOLS: "9477386"
  SECURE_FILES_DOWNLOAD_PATH: './'
  ANDROID_KEYSTORE_FILE: '/builds/x/app/android/my-upload-key.keystore'
 
clean-build-job:        
 stage: build
  image: openjdk:11-jdk
  before_script:
    # # Update package list and install required packages
    - apt-get --quiet update --yes
    - apt-get --quiet install --yes wget unzip curl ruby ruby-dev build-essential libffi-dev libgmp-dev
    - curl -sL https://deb.nodesource.com/setup_19.x | bash -
    - apt-get install -y nodejs
    - 
    # Install Fastlane
    - gem install bundler
    - gem install bundler:1.17.2
    - bundle install
    
    - export ANDROID_SDK_ROOT="${PWD}/android-home"
    - install -d $ANDROID_SDK_ROOT
    - wget --output-document=$ANDROID_SDK_ROOT/cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
    - pushd $ANDROID_SDK_ROOT
    - unzip -d cmdline-tools cmdline-tools.zip
    - pushd cmdline-tools
    - mv cmdline-tools tools || true
    - popd
    - popd
    - export PATH=$PATH:${ANDROID_SDK_ROOT}/cmdline-tools/tools/bin/

    # Nothing fancy here, just checking sdkManager version
    - sdkmanager --version

    # use yes to accept all licenses
    - yes | sdkmanager --licenses || true
    - sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}" --include_obsolete
    - sdkmanager "platform-tools" --include_obsolete
    - sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}" --include_obsolete
    - ls
    - npm i @react-native-community/cli-platform-android
    - cd android
  script:
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    - ./gradlew --stop
    - gem install bundler
    - bundle install
    - fastlane build_apk
```

### Platforms

Android
